-- lifecycle-engine JDBC schema, H2 dialect. Same tables and column names as PostgreSQL, with the three things
-- H2 does not have: no `timestamptz` (spelled `timestamp(6) with time zone`), no `bigserial` (`identity`), and
-- no partial indexes (the single-ACTIVE rule is enforced with a generated column, as in MySQL, because H2 keeps
-- NULLs distinct in a unique index).

create table if not exists lifecycle_state (
  tenant_id     varchar(64)  not null default '',   -- '' = no tenant; part of the key so nulls never collide
  entity_type   varchar(64)  not null,
  entity_id     varchar(128) not null,
  state         varchar(128) not null,
  version       bigint       not null,
  updated_at    timestamp(6) with time zone not null,
  last_event_id varchar(64)  not null,
  rule_set_version varchar(128),
  primary key (tenant_id, entity_type, entity_id)
);
create index if not exists lifecycle_state_by_state on lifecycle_state (entity_type, state, tenant_id);

create table if not exists lifecycle_inbox (
  tenant_id     varchar(64)  not null default '',
  entity_type   varchar(64)  not null,
  entity_id     varchar(128) not null,
  event_id      varchar(64)  not null,
  audit_id      varchar(64)  not null,
  expires_at    timestamp(6) with time zone not null,
  primary key (tenant_id, entity_type, entity_id, event_id)
);
create index if not exists lifecycle_inbox_expiry on lifecycle_inbox (expires_at);

create table if not exists lifecycle_audit (
  audit_id       varchar(64)  primary key,
  event_id       varchar(64)  not null,
  tenant_id      varchar(64),
  entity_type    varchar(64)  not null,
  entity_id      varchar(128) not null,
  action         varchar(128) not null,
  actor_id       varchar(128) not null,
  actor_roles    varchar(4000) not null,           -- JSON array
  actor_kind     varchar(16)  not null,
  from_state     varchar(128),
  to_state       varchar(128),
  transition_id  varchar(128),
  outcome        varchar(16)  not null,            -- APPLIED | REFUSED | CONFLICTED | DUPLICATE
  reason         varchar(32),
  detail         varchar(4000),
  rule_set_version varchar(128),
  at             timestamp(6) with time zone not null,
  correlation_id varchar(64)  not null,
  causation_id   varchar(64),
  hop            integer      not null
);
create index if not exists lifecycle_audit_by_entity on lifecycle_audit (entity_type, entity_id, at);
create index if not exists lifecycle_audit_by_event on lifecycle_audit (event_id);
create index if not exists lifecycle_audit_by_correlation on lifecycle_audit (correlation_id, hop);

create table if not exists lifecycle_outbox (
  event_id     varchar(64)  primary key,
  body         clob         not null,              -- the full LifecycleEvent as JSON
  created_at   timestamp(6) with time zone not null,
  sent_at      timestamp(6) with time zone
);
create index if not exists lifecycle_outbox_unsent on lifecycle_outbox (sent_at, created_at);

create table if not exists lifecycle_rule_set (
  id            bigint generated by default as identity primary key,
  tenant_id     varchar(64),                       -- null = the base rule set
  entity_type   varchar(64)  not null,
  version       integer      not null,
  status        varchar(16)  not null,             -- DRAFT | ACTIVE | RETIRED
  format        varchar(8)   not null,             -- yaml | json
  body          clob         not null,
  created_by    varchar(128) not null,
  created_at    timestamp(6) with time zone not null,
  activated_at  timestamp(6) with time zone,
  -- non-null only for ACTIVE rows, so any number of DRAFT/RETIRED rows coexist under the unique constraint
  active_key    varchar(130) generated always as (case when status = 'ACTIVE' then concat(coalesce(tenant_id, ''), '|', entity_type) end),
  constraint lifecycle_rule_set_version unique (tenant_id, entity_type, version),
  constraint lifecycle_rule_set_active unique (active_key)
);

create table if not exists lifecycle_task (
  task_id        varchar(64)  primary key,
  tenant_id      varchar(64),
  name           varchar(128) not null,
  assign_to      varchar(2000) not null,           -- JSON array of roles
  created_by_type varchar(64) not null,
  created_by_id  varchar(128) not null,
  created_by_event_id varchar(64) not null,
  on_complete_action varchar(128) not null,
  target_type    varchar(64)  not null,
  target_id      varchar(128) not null,
  payload        clob         not null,            -- JSON object
  status         varchar(16)  not null,            -- OPEN | CLAIMED | COMPLETED | CANCELLED
  claimed_by     varchar(128),
  created_at     timestamp(6) with time zone not null,
  updated_at     timestamp(6) with time zone not null,
  correlation_id varchar(64)  not null,
  causation_id   varchar(64),
  hop            integer      not null
);
create index if not exists lifecycle_task_open on lifecycle_task (status, tenant_id, created_at);
create index if not exists lifecycle_task_by_entity on lifecycle_task (created_by_type, created_by_id);
